// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: painting_message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_painting_5fmessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_painting_5fmessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_painting_5fmessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_painting_5fmessage_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_painting_5fmessage_2eproto;
namespace PaintingMessage {
class CommonResponse;
class CommonResponseDefaultTypeInternal;
extern CommonResponseDefaultTypeInternal _CommonResponse_default_instance_;
class DataPackage;
class DataPackageDefaultTypeInternal;
extern DataPackageDefaultTypeInternal _DataPackage_default_instance_;
class ModelInputData;
class ModelInputDataDefaultTypeInternal;
extern ModelInputDataDefaultTypeInternal _ModelInputData_default_instance_;
class RegisterApp;
class RegisterAppDefaultTypeInternal;
extern RegisterAppDefaultTypeInternal _RegisterApp_default_instance_;
}  // namespace PaintingMessage
PROTOBUF_NAMESPACE_OPEN
template<> ::PaintingMessage::CommonResponse* Arena::CreateMaybeMessage<::PaintingMessage::CommonResponse>(Arena*);
template<> ::PaintingMessage::DataPackage* Arena::CreateMaybeMessage<::PaintingMessage::DataPackage>(Arena*);
template<> ::PaintingMessage::ModelInputData* Arena::CreateMaybeMessage<::PaintingMessage::ModelInputData>(Arena*);
template<> ::PaintingMessage::RegisterApp* Arena::CreateMaybeMessage<::PaintingMessage::RegisterApp>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace PaintingMessage {

enum ErrorCode : int {
  kErrorNone = 0,
  kErrorAppRegisterExist = 1,
  kErrorAppRegisterType = 2,
  kErrorAppRegisterLimit = 3,
  kErrorOther = 5,
  ErrorCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ErrorCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ErrorCode_IsValid(int value);
constexpr ErrorCode ErrorCode_MIN = kErrorNone;
constexpr ErrorCode ErrorCode_MAX = kErrorOther;
constexpr int ErrorCode_ARRAYSIZE = ErrorCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ErrorCode_descriptor();
template<typename T>
inline const std::string& ErrorCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ErrorCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ErrorCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ErrorCode_descriptor(), enum_t_value);
}
inline bool ErrorCode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ErrorCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ErrorCode>(
    ErrorCode_descriptor(), name, value);
}
// ===================================================================

class CommonResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PaintingMessage.CommonResponse) */ {
 public:
  inline CommonResponse() : CommonResponse(nullptr) {}
  virtual ~CommonResponse();

  CommonResponse(const CommonResponse& from);
  CommonResponse(CommonResponse&& from) noexcept
    : CommonResponse() {
    *this = ::std::move(from);
  }

  inline CommonResponse& operator=(const CommonResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CommonResponse& operator=(CommonResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CommonResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CommonResponse* internal_default_instance() {
    return reinterpret_cast<const CommonResponse*>(
               &_CommonResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CommonResponse& a, CommonResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(CommonResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CommonResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CommonResponse* New() const final {
    return CreateMaybeMessage<CommonResponse>(nullptr);
  }

  CommonResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CommonResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CommonResponse& from);
  void MergeFrom(const CommonResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CommonResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PaintingMessage.CommonResponse";
  }
  protected:
  explicit CommonResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_painting_5fmessage_2eproto);
    return ::descriptor_table_painting_5fmessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kRetFieldNumber = 1,
  };
  // string message = 2;
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // .PaintingMessage.ErrorCode ret = 1;
  void clear_ret();
  ::PaintingMessage::ErrorCode ret() const;
  void set_ret(::PaintingMessage::ErrorCode value);
  private:
  ::PaintingMessage::ErrorCode _internal_ret() const;
  void _internal_set_ret(::PaintingMessage::ErrorCode value);
  public:

  // @@protoc_insertion_point(class_scope:PaintingMessage.CommonResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  int ret_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_painting_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class RegisterApp PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PaintingMessage.RegisterApp) */ {
 public:
  inline RegisterApp() : RegisterApp(nullptr) {}
  virtual ~RegisterApp();

  RegisterApp(const RegisterApp& from);
  RegisterApp(RegisterApp&& from) noexcept
    : RegisterApp() {
    *this = ::std::move(from);
  }

  inline RegisterApp& operator=(const RegisterApp& from) {
    CopyFrom(from);
    return *this;
  }
  inline RegisterApp& operator=(RegisterApp&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RegisterApp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RegisterApp* internal_default_instance() {
    return reinterpret_cast<const RegisterApp*>(
               &_RegisterApp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RegisterApp& a, RegisterApp& b) {
    a.Swap(&b);
  }
  inline void Swap(RegisterApp* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RegisterApp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RegisterApp* New() const final {
    return CreateMaybeMessage<RegisterApp>(nullptr);
  }

  RegisterApp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RegisterApp>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RegisterApp& from);
  void MergeFrom(const RegisterApp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RegisterApp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PaintingMessage.RegisterApp";
  }
  protected:
  explicit RegisterApp(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_painting_5fmessage_2eproto);
    return ::descriptor_table_painting_5fmessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // string id = 1;
  void clear_id();
  const std::string& id() const;
  void set_id(const std::string& value);
  void set_id(std::string&& value);
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  std::string* mutable_id();
  std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // string type = 2;
  void clear_type();
  const std::string& type() const;
  void set_type(const std::string& value);
  void set_type(std::string&& value);
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  std::string* mutable_type();
  std::string* release_type();
  void set_allocated_type(std::string* type);
  private:
  const std::string& _internal_type() const;
  void _internal_set_type(const std::string& value);
  std::string* _internal_mutable_type();
  public:

  // @@protoc_insertion_point(class_scope:PaintingMessage.RegisterApp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_painting_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class ModelInputData PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PaintingMessage.ModelInputData) */ {
 public:
  inline ModelInputData() : ModelInputData(nullptr) {}
  virtual ~ModelInputData();

  ModelInputData(const ModelInputData& from);
  ModelInputData(ModelInputData&& from) noexcept
    : ModelInputData() {
    *this = ::std::move(from);
  }

  inline ModelInputData& operator=(const ModelInputData& from) {
    CopyFrom(from);
    return *this;
  }
  inline ModelInputData& operator=(ModelInputData&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ModelInputData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ModelInputData* internal_default_instance() {
    return reinterpret_cast<const ModelInputData*>(
               &_ModelInputData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ModelInputData& a, ModelInputData& b) {
    a.Swap(&b);
  }
  inline void Swap(ModelInputData* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ModelInputData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ModelInputData* New() const final {
    return CreateMaybeMessage<ModelInputData>(nullptr);
  }

  ModelInputData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ModelInputData>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ModelInputData& from);
  void MergeFrom(const ModelInputData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ModelInputData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PaintingMessage.ModelInputData";
  }
  protected:
  explicit ModelInputData(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_painting_5fmessage_2eproto);
    return ::descriptor_table_painting_5fmessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kDataFieldNumber = 2,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // bytes data = 2;
  void clear_data();
  const std::string& data() const;
  void set_data(const std::string& value);
  void set_data(std::string&& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  std::string* mutable_data();
  std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // @@protoc_insertion_point(class_scope:PaintingMessage.ModelInputData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_painting_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class DataPackage PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PaintingMessage.DataPackage) */ {
 public:
  inline DataPackage() : DataPackage(nullptr) {}
  virtual ~DataPackage();

  DataPackage(const DataPackage& from);
  DataPackage(DataPackage&& from) noexcept
    : DataPackage() {
    *this = ::std::move(from);
  }

  inline DataPackage& operator=(const DataPackage& from) {
    CopyFrom(from);
    return *this;
  }
  inline DataPackage& operator=(DataPackage&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DataPackage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DataPackage* internal_default_instance() {
    return reinterpret_cast<const DataPackage*>(
               &_DataPackage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(DataPackage& a, DataPackage& b) {
    a.Swap(&b);
  }
  inline void Swap(DataPackage* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DataPackage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DataPackage* New() const final {
    return CreateMaybeMessage<DataPackage>(nullptr);
  }

  DataPackage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DataPackage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DataPackage& from);
  void MergeFrom(const DataPackage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DataPackage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PaintingMessage.DataPackage";
  }
  protected:
  explicit DataPackage(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_painting_5fmessage_2eproto);
    return ::descriptor_table_painting_5fmessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectDataFieldNumber = 1,
    kLayoutDataFieldNumber = 2,
  };
  // .PaintingMessage.ModelInputData objectData = 1;
  bool has_objectdata() const;
  private:
  bool _internal_has_objectdata() const;
  public:
  void clear_objectdata();
  const ::PaintingMessage::ModelInputData& objectdata() const;
  ::PaintingMessage::ModelInputData* release_objectdata();
  ::PaintingMessage::ModelInputData* mutable_objectdata();
  void set_allocated_objectdata(::PaintingMessage::ModelInputData* objectdata);
  private:
  const ::PaintingMessage::ModelInputData& _internal_objectdata() const;
  ::PaintingMessage::ModelInputData* _internal_mutable_objectdata();
  public:
  void unsafe_arena_set_allocated_objectdata(
      ::PaintingMessage::ModelInputData* objectdata);
  ::PaintingMessage::ModelInputData* unsafe_arena_release_objectdata();

  // .PaintingMessage.ModelInputData layoutData = 2;
  bool has_layoutdata() const;
  private:
  bool _internal_has_layoutdata() const;
  public:
  void clear_layoutdata();
  const ::PaintingMessage::ModelInputData& layoutdata() const;
  ::PaintingMessage::ModelInputData* release_layoutdata();
  ::PaintingMessage::ModelInputData* mutable_layoutdata();
  void set_allocated_layoutdata(::PaintingMessage::ModelInputData* layoutdata);
  private:
  const ::PaintingMessage::ModelInputData& _internal_layoutdata() const;
  ::PaintingMessage::ModelInputData* _internal_mutable_layoutdata();
  public:
  void unsafe_arena_set_allocated_layoutdata(
      ::PaintingMessage::ModelInputData* layoutdata);
  ::PaintingMessage::ModelInputData* unsafe_arena_release_layoutdata();

  // @@protoc_insertion_point(class_scope:PaintingMessage.DataPackage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PaintingMessage::ModelInputData* objectdata_;
  ::PaintingMessage::ModelInputData* layoutdata_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_painting_5fmessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CommonResponse

// .PaintingMessage.ErrorCode ret = 1;
inline void CommonResponse::clear_ret() {
  ret_ = 0;
}
inline ::PaintingMessage::ErrorCode CommonResponse::_internal_ret() const {
  return static_cast< ::PaintingMessage::ErrorCode >(ret_);
}
inline ::PaintingMessage::ErrorCode CommonResponse::ret() const {
  // @@protoc_insertion_point(field_get:PaintingMessage.CommonResponse.ret)
  return _internal_ret();
}
inline void CommonResponse::_internal_set_ret(::PaintingMessage::ErrorCode value) {
  
  ret_ = value;
}
inline void CommonResponse::set_ret(::PaintingMessage::ErrorCode value) {
  _internal_set_ret(value);
  // @@protoc_insertion_point(field_set:PaintingMessage.CommonResponse.ret)
}

// string message = 2;
inline void CommonResponse::clear_message() {
  message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& CommonResponse::message() const {
  // @@protoc_insertion_point(field_get:PaintingMessage.CommonResponse.message)
  return _internal_message();
}
inline void CommonResponse::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:PaintingMessage.CommonResponse.message)
}
inline std::string* CommonResponse::mutable_message() {
  // @@protoc_insertion_point(field_mutable:PaintingMessage.CommonResponse.message)
  return _internal_mutable_message();
}
inline const std::string& CommonResponse::_internal_message() const {
  return message_.Get();
}
inline void CommonResponse::_internal_set_message(const std::string& value) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void CommonResponse::set_message(std::string&& value) {
  
  message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PaintingMessage.CommonResponse.message)
}
inline void CommonResponse::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PaintingMessage.CommonResponse.message)
}
inline void CommonResponse::set_message(const char* value,
    size_t size) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PaintingMessage.CommonResponse.message)
}
inline std::string* CommonResponse::_internal_mutable_message() {
  
  return message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* CommonResponse::release_message() {
  // @@protoc_insertion_point(field_release:PaintingMessage.CommonResponse.message)
  return message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CommonResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PaintingMessage.CommonResponse.message)
}

// -------------------------------------------------------------------

// RegisterApp

// string id = 1;
inline void RegisterApp::clear_id() {
  id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& RegisterApp::id() const {
  // @@protoc_insertion_point(field_get:PaintingMessage.RegisterApp.id)
  return _internal_id();
}
inline void RegisterApp::set_id(const std::string& value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:PaintingMessage.RegisterApp.id)
}
inline std::string* RegisterApp::mutable_id() {
  // @@protoc_insertion_point(field_mutable:PaintingMessage.RegisterApp.id)
  return _internal_mutable_id();
}
inline const std::string& RegisterApp::_internal_id() const {
  return id_.Get();
}
inline void RegisterApp::_internal_set_id(const std::string& value) {
  
  id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void RegisterApp::set_id(std::string&& value) {
  
  id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PaintingMessage.RegisterApp.id)
}
inline void RegisterApp::set_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PaintingMessage.RegisterApp.id)
}
inline void RegisterApp::set_id(const char* value,
    size_t size) {
  
  id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PaintingMessage.RegisterApp.id)
}
inline std::string* RegisterApp::_internal_mutable_id() {
  
  return id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* RegisterApp::release_id() {
  // @@protoc_insertion_point(field_release:PaintingMessage.RegisterApp.id)
  return id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void RegisterApp::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PaintingMessage.RegisterApp.id)
}

// string type = 2;
inline void RegisterApp::clear_type() {
  type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& RegisterApp::type() const {
  // @@protoc_insertion_point(field_get:PaintingMessage.RegisterApp.type)
  return _internal_type();
}
inline void RegisterApp::set_type(const std::string& value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:PaintingMessage.RegisterApp.type)
}
inline std::string* RegisterApp::mutable_type() {
  // @@protoc_insertion_point(field_mutable:PaintingMessage.RegisterApp.type)
  return _internal_mutable_type();
}
inline const std::string& RegisterApp::_internal_type() const {
  return type_.Get();
}
inline void RegisterApp::_internal_set_type(const std::string& value) {
  
  type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void RegisterApp::set_type(std::string&& value) {
  
  type_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PaintingMessage.RegisterApp.type)
}
inline void RegisterApp::set_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PaintingMessage.RegisterApp.type)
}
inline void RegisterApp::set_type(const char* value,
    size_t size) {
  
  type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PaintingMessage.RegisterApp.type)
}
inline std::string* RegisterApp::_internal_mutable_type() {
  
  return type_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* RegisterApp::release_type() {
  // @@protoc_insertion_point(field_release:PaintingMessage.RegisterApp.type)
  return type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void RegisterApp::set_allocated_type(std::string* type) {
  if (type != nullptr) {
    
  } else {
    
  }
  type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), type,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PaintingMessage.RegisterApp.type)
}

// -------------------------------------------------------------------

// ModelInputData

// string name = 1;
inline void ModelInputData::clear_name() {
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ModelInputData::name() const {
  // @@protoc_insertion_point(field_get:PaintingMessage.ModelInputData.name)
  return _internal_name();
}
inline void ModelInputData::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:PaintingMessage.ModelInputData.name)
}
inline std::string* ModelInputData::mutable_name() {
  // @@protoc_insertion_point(field_mutable:PaintingMessage.ModelInputData.name)
  return _internal_mutable_name();
}
inline const std::string& ModelInputData::_internal_name() const {
  return name_.Get();
}
inline void ModelInputData::_internal_set_name(const std::string& value) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ModelInputData::set_name(std::string&& value) {
  
  name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PaintingMessage.ModelInputData.name)
}
inline void ModelInputData::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PaintingMessage.ModelInputData.name)
}
inline void ModelInputData::set_name(const char* value,
    size_t size) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PaintingMessage.ModelInputData.name)
}
inline std::string* ModelInputData::_internal_mutable_name() {
  
  return name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ModelInputData::release_name() {
  // @@protoc_insertion_point(field_release:PaintingMessage.ModelInputData.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ModelInputData::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PaintingMessage.ModelInputData.name)
}

// bytes data = 2;
inline void ModelInputData::clear_data() {
  data_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ModelInputData::data() const {
  // @@protoc_insertion_point(field_get:PaintingMessage.ModelInputData.data)
  return _internal_data();
}
inline void ModelInputData::set_data(const std::string& value) {
  _internal_set_data(value);
  // @@protoc_insertion_point(field_set:PaintingMessage.ModelInputData.data)
}
inline std::string* ModelInputData::mutable_data() {
  // @@protoc_insertion_point(field_mutable:PaintingMessage.ModelInputData.data)
  return _internal_mutable_data();
}
inline const std::string& ModelInputData::_internal_data() const {
  return data_.Get();
}
inline void ModelInputData::_internal_set_data(const std::string& value) {
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ModelInputData::set_data(std::string&& value) {
  
  data_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PaintingMessage.ModelInputData.data)
}
inline void ModelInputData::set_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PaintingMessage.ModelInputData.data)
}
inline void ModelInputData::set_data(const void* value,
    size_t size) {
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PaintingMessage.ModelInputData.data)
}
inline std::string* ModelInputData::_internal_mutable_data() {
  
  return data_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ModelInputData::release_data() {
  // @@protoc_insertion_point(field_release:PaintingMessage.ModelInputData.data)
  return data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ModelInputData::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PaintingMessage.ModelInputData.data)
}

// -------------------------------------------------------------------

// DataPackage

// .PaintingMessage.ModelInputData objectData = 1;
inline bool DataPackage::_internal_has_objectdata() const {
  return this != internal_default_instance() && objectdata_ != nullptr;
}
inline bool DataPackage::has_objectdata() const {
  return _internal_has_objectdata();
}
inline void DataPackage::clear_objectdata() {
  if (GetArena() == nullptr && objectdata_ != nullptr) {
    delete objectdata_;
  }
  objectdata_ = nullptr;
}
inline const ::PaintingMessage::ModelInputData& DataPackage::_internal_objectdata() const {
  const ::PaintingMessage::ModelInputData* p = objectdata_;
  return p != nullptr ? *p : *reinterpret_cast<const ::PaintingMessage::ModelInputData*>(
      &::PaintingMessage::_ModelInputData_default_instance_);
}
inline const ::PaintingMessage::ModelInputData& DataPackage::objectdata() const {
  // @@protoc_insertion_point(field_get:PaintingMessage.DataPackage.objectData)
  return _internal_objectdata();
}
inline void DataPackage::unsafe_arena_set_allocated_objectdata(
    ::PaintingMessage::ModelInputData* objectdata) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(objectdata_);
  }
  objectdata_ = objectdata;
  if (objectdata) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PaintingMessage.DataPackage.objectData)
}
inline ::PaintingMessage::ModelInputData* DataPackage::release_objectdata() {
  
  ::PaintingMessage::ModelInputData* temp = objectdata_;
  objectdata_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::PaintingMessage::ModelInputData* DataPackage::unsafe_arena_release_objectdata() {
  // @@protoc_insertion_point(field_release:PaintingMessage.DataPackage.objectData)
  
  ::PaintingMessage::ModelInputData* temp = objectdata_;
  objectdata_ = nullptr;
  return temp;
}
inline ::PaintingMessage::ModelInputData* DataPackage::_internal_mutable_objectdata() {
  
  if (objectdata_ == nullptr) {
    auto* p = CreateMaybeMessage<::PaintingMessage::ModelInputData>(GetArena());
    objectdata_ = p;
  }
  return objectdata_;
}
inline ::PaintingMessage::ModelInputData* DataPackage::mutable_objectdata() {
  // @@protoc_insertion_point(field_mutable:PaintingMessage.DataPackage.objectData)
  return _internal_mutable_objectdata();
}
inline void DataPackage::set_allocated_objectdata(::PaintingMessage::ModelInputData* objectdata) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete objectdata_;
  }
  if (objectdata) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(objectdata);
    if (message_arena != submessage_arena) {
      objectdata = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, objectdata, submessage_arena);
    }
    
  } else {
    
  }
  objectdata_ = objectdata;
  // @@protoc_insertion_point(field_set_allocated:PaintingMessage.DataPackage.objectData)
}

// .PaintingMessage.ModelInputData layoutData = 2;
inline bool DataPackage::_internal_has_layoutdata() const {
  return this != internal_default_instance() && layoutdata_ != nullptr;
}
inline bool DataPackage::has_layoutdata() const {
  return _internal_has_layoutdata();
}
inline void DataPackage::clear_layoutdata() {
  if (GetArena() == nullptr && layoutdata_ != nullptr) {
    delete layoutdata_;
  }
  layoutdata_ = nullptr;
}
inline const ::PaintingMessage::ModelInputData& DataPackage::_internal_layoutdata() const {
  const ::PaintingMessage::ModelInputData* p = layoutdata_;
  return p != nullptr ? *p : *reinterpret_cast<const ::PaintingMessage::ModelInputData*>(
      &::PaintingMessage::_ModelInputData_default_instance_);
}
inline const ::PaintingMessage::ModelInputData& DataPackage::layoutdata() const {
  // @@protoc_insertion_point(field_get:PaintingMessage.DataPackage.layoutData)
  return _internal_layoutdata();
}
inline void DataPackage::unsafe_arena_set_allocated_layoutdata(
    ::PaintingMessage::ModelInputData* layoutdata) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(layoutdata_);
  }
  layoutdata_ = layoutdata;
  if (layoutdata) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PaintingMessage.DataPackage.layoutData)
}
inline ::PaintingMessage::ModelInputData* DataPackage::release_layoutdata() {
  
  ::PaintingMessage::ModelInputData* temp = layoutdata_;
  layoutdata_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::PaintingMessage::ModelInputData* DataPackage::unsafe_arena_release_layoutdata() {
  // @@protoc_insertion_point(field_release:PaintingMessage.DataPackage.layoutData)
  
  ::PaintingMessage::ModelInputData* temp = layoutdata_;
  layoutdata_ = nullptr;
  return temp;
}
inline ::PaintingMessage::ModelInputData* DataPackage::_internal_mutable_layoutdata() {
  
  if (layoutdata_ == nullptr) {
    auto* p = CreateMaybeMessage<::PaintingMessage::ModelInputData>(GetArena());
    layoutdata_ = p;
  }
  return layoutdata_;
}
inline ::PaintingMessage::ModelInputData* DataPackage::mutable_layoutdata() {
  // @@protoc_insertion_point(field_mutable:PaintingMessage.DataPackage.layoutData)
  return _internal_mutable_layoutdata();
}
inline void DataPackage::set_allocated_layoutdata(::PaintingMessage::ModelInputData* layoutdata) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete layoutdata_;
  }
  if (layoutdata) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(layoutdata);
    if (message_arena != submessage_arena) {
      layoutdata = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, layoutdata, submessage_arena);
    }
    
  } else {
    
  }
  layoutdata_ = layoutdata;
  // @@protoc_insertion_point(field_set_allocated:PaintingMessage.DataPackage.layoutData)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace PaintingMessage

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::PaintingMessage::ErrorCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PaintingMessage::ErrorCode>() {
  return ::PaintingMessage::ErrorCode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_painting_5fmessage_2eproto
