arch: NestedUNet
batch_size: 12
dataset: customer_dataset
deep_supervision: false
early_stopping: -1
epochs: 100
factor: 0.1
gamma: 0.6666666666666666
img_ext: .png
input_channels: 3
input_dir: ./
input_h: 96
input_w: 96
loss: LovaszHingeLoss
lr: 0.001
mask_ext: .png
milestones: 1,2
min_lr: 1.0e-05
momentum: 0.9
name: customer_dataset_NestedUNet_woDS
nesterov: false
num_classes: 1
num_workers: 4
optimizer: SGD
out_dir: ./
patience: 2
scheduler: CosineAnnealingLR
trained_model: nested_unet.pth
transfer_training: true
weight_decay: 0.0001
