_BASE_: "../Base-RCNN-FPN.yaml"
INPUT:
  FIX_SHAPE: (1344, 1344)
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
DATALOADER:
  ASPECT_RATIO_GROUPING: False
