# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: painting_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='painting_message.proto',
  package='PaintingMessage',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16painting_message.proto\x12\x0fPaintingMessage\"J\n\x0e\x43ommonResponse\x12\'\n\x03ret\x18\x01 \x01(\x0e\x32\x1a.PaintingMessage.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\"\'\n\x0bRegisterApp\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\",\n\x0eModelInputData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"w\n\x0b\x44\x61taPackage\x12\x33\n\nobjectData\x18\x01 \x01(\x0b\x32\x1f.PaintingMessage.ModelInputData\x12\x33\n\nlayoutData\x18\x02 \x01(\x0b\x32\x1f.PaintingMessage.ModelInputData*\x7f\n\tErrorCode\x12\x0e\n\nkErrorNone\x10\x00\x12\x1a\n\x16kErrorAppRegisterExist\x10\x01\x12\x19\n\x15kErrorAppRegisterType\x10\x02\x12\x1a\n\x16kErrorAppRegisterLimit\x10\x03\x12\x0f\n\x0bkErrorOther\x10\x05\x62\x06proto3')
)

_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='PaintingMessage.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='kErrorNone', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kErrorAppRegisterExist', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kErrorAppRegisterType', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kErrorAppRegisterLimit', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kErrorOther', index=4, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=327,
  serialized_end=454,
)
_sym_db.RegisterEnumDescriptor(_ERRORCODE)

ErrorCode = enum_type_wrapper.EnumTypeWrapper(_ERRORCODE)
kErrorNone = 0
kErrorAppRegisterExist = 1
kErrorAppRegisterType = 2
kErrorAppRegisterLimit = 3
kErrorOther = 5



_COMMONRESPONSE = _descriptor.Descriptor(
  name='CommonResponse',
  full_name='PaintingMessage.CommonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='PaintingMessage.CommonResponse.ret', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='PaintingMessage.CommonResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=117,
)


_REGISTERAPP = _descriptor.Descriptor(
  name='RegisterApp',
  full_name='PaintingMessage.RegisterApp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PaintingMessage.RegisterApp.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='PaintingMessage.RegisterApp.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=158,
)


_MODELINPUTDATA = _descriptor.Descriptor(
  name='ModelInputData',
  full_name='PaintingMessage.ModelInputData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PaintingMessage.ModelInputData.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='PaintingMessage.ModelInputData.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=204,
)


_DATAPACKAGE = _descriptor.Descriptor(
  name='DataPackage',
  full_name='PaintingMessage.DataPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='objectData', full_name='PaintingMessage.DataPackage.objectData', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layoutData', full_name='PaintingMessage.DataPackage.layoutData', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=325,
)

_COMMONRESPONSE.fields_by_name['ret'].enum_type = _ERRORCODE
_DATAPACKAGE.fields_by_name['objectData'].message_type = _MODELINPUTDATA
_DATAPACKAGE.fields_by_name['layoutData'].message_type = _MODELINPUTDATA
DESCRIPTOR.message_types_by_name['CommonResponse'] = _COMMONRESPONSE
DESCRIPTOR.message_types_by_name['RegisterApp'] = _REGISTERAPP
DESCRIPTOR.message_types_by_name['ModelInputData'] = _MODELINPUTDATA
DESCRIPTOR.message_types_by_name['DataPackage'] = _DATAPACKAGE
DESCRIPTOR.enum_types_by_name['ErrorCode'] = _ERRORCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommonResponse = _reflection.GeneratedProtocolMessageType('CommonResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMMONRESPONSE,
  '__module__' : 'painting_message_pb2'
  # @@protoc_insertion_point(class_scope:PaintingMessage.CommonResponse)
  })
_sym_db.RegisterMessage(CommonResponse)

RegisterApp = _reflection.GeneratedProtocolMessageType('RegisterApp', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERAPP,
  '__module__' : 'painting_message_pb2'
  # @@protoc_insertion_point(class_scope:PaintingMessage.RegisterApp)
  })
_sym_db.RegisterMessage(RegisterApp)

ModelInputData = _reflection.GeneratedProtocolMessageType('ModelInputData', (_message.Message,), {
  'DESCRIPTOR' : _MODELINPUTDATA,
  '__module__' : 'painting_message_pb2'
  # @@protoc_insertion_point(class_scope:PaintingMessage.ModelInputData)
  })
_sym_db.RegisterMessage(ModelInputData)

DataPackage = _reflection.GeneratedProtocolMessageType('DataPackage', (_message.Message,), {
  'DESCRIPTOR' : _DATAPACKAGE,
  '__module__' : 'painting_message_pb2'
  # @@protoc_insertion_point(class_scope:PaintingMessage.DataPackage)
  })
_sym_db.RegisterMessage(DataPackage)


# @@protoc_insertion_point(module_scope)
