footprint: [[0.3,0.29], [0.3,-0.29], [-0.3,-0.29], [-0.3,0.29]] # SCOUT MINI



transform_tolerance: 0.2
map_type: costmap

obstacle_layer:
 enabled: true
 obstacle_range: 3.0
 raytrace_range: 4.0
 inflation_radius: 0.1
 track_unknown_space: true
 combination_method: 1

 laser_scan_sensor: { data_type: LaserScan, topic: scan, marking: true, clearing: true,
                      max_obstacle_height: 10.0, min_obstacle_height: -10.0,
                      obstacle_range: 5.0, raytrace_range: 6.0 }


global_inflation_layer:
 enabled: true
 cost_scaling_factor: 3
 inflation_radius: 0.5

local_inflation_layer:
 enabled: true
 cost_scaling_factor: 10.0  # exponential rate at which the obstacle cost drops off (default: 10)
 inflation_radius: 0.2 # 0.1

static_layer:
  enabled:              true
  map_topic:            "map"
