local_costmap:
  global_frame: map
  robot_base_frame: base_link
  robot_radius: 0.3
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 1.5
  height: 1.5
  resolution: 0.1
  transform_tolerance: 0.5

  plugins:
    - { name: static_layer,        type: "costmap_2d::StaticLayer" }
    - { name: obstacle_layer,      type: "costmap_2d::ObstacleLayer" }
    - { name: local_inflation_layer,         type: "costmap_2d::InflationLayer" }

