footprint: [ [ -0.30, -0.29 ], [ -0.30, 0.29 ], [ 0.30, 0.29 ], [ 0.30, -0.29 ] ]

footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.1

obstacle_range: 3.0
raytrace_range: 4.0

#layer definitions
static:
  map_topic: map
  subscribe_to_updates: true

obstacle_layer:
  enabled: true
  obstacle_range: 3.0
  raytrace_range: 4.0
  inflation_radius: 0.05
  track_unknown_space: true
  combination_method: 1

  observation_sources: laser_scan_sensor
  laser_scan_sensor: { data_type: LaserScan, topic: scan, marking: true, clearing: true }

global_inflation:
  inflation_radius: 1.0
  cost_scaling_factor: 10.0  # exponential rate at which the obstacle cost drops off (default: 10)

local_inflation:
  inflation_radius: 0.2
  cost_scaling_factor: 10.0  # exponential rate at which the obstacle cost drops off (default: 10)
