global_costmap:
  global_frame: map
  robot_base_frame: base_link
  transform_tolerance: 2.0
  update_frequency: 2.0
  publish_frequency: 2.0
  static_map: true
  rolling_window: false

  width: 100.0
  height: 100.0
  resolution: 0.05

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: rgbd_obstacle_layer, type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
    - {name: global_inflation_layer, type: "costmap_2d::InflationLayer"}
