local_costmap:
  global_frame: map
  robot_base_frame: base_link
  transform_tolerance: 2.0
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 5
  height: 5
  resolution: 0.05


  plugins:
    - {name: rgbd_obstacle_layer, type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
    - {name: local_inflation_layer, type: "costmap_2d::InflationLayer"}