/**
* Copyright (c) Huawei Technologies Co., Ltd. 2020-2022. All rights reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at

* http://www.apache.org/licenses/LICENSE-2.0

* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.

* File label.h
* Description: label result
*/
#ifndef modelInference_label_H
#define modelInference_label_H

const std::string label[] ={"tenchTinca tinca",
"goldfishCarassius auratus", "great white sharkwhite sharkman-eaterman-eating sharkCarcharodon carcharias",
"tiger sharkGaleocerdo cuvieri", "hammerheadhammerhead shark",
"electric raycrampfishnumbfishtorpedo", "stingray", "cock", "hen",
"ostrichStruthio camelus", "bramblingFringilla montifringilla",
"goldfinchCarduelis carduelis", "house finchlinnetCarpodacus mexicanus",
"juncosnowbird", "indigo buntingindigo finchindigo birdPasserina cyanea",
"robinAmerican robinTurdus migratorius", "bulbul", "jay", "magpie", "chickadee",
"water ouzeldipper", "kite", "bald eagleAmerican eagleHaliaeetus leucocephalus",
"vulture", "great grey owlgreat gray owlStrix nebulosa",
"European fire salamanderSalamandra salamandra",
"common newtTriturus vulgaris", "eft", "spotted salamanderAmbystoma maculatum",
"axolotlmud puppyAmbystoma mexicanum", "bullfrogRana catesbeiana", "tree frogtree-frog",
"tailed frogbell toadribbed toadtailed toadAscaphus trui",
"loggerheadloggerhead turtleCaretta caretta",
"leatherback turtleleatherbackleathery turtleDermochelys coriacea",
"mud turtle", "terrapin", "box turtlebox tortoise", "banded gecko",
"common iguanaiguanaIguana iguana", "American chameleonanoleAnolis carolinensis",
"whiptailwhiptail lizard", "agama", "frilled lizardChlamydosaurus kingi",
"alligator lizard", "Gila monsterHeloderma suspectum",
"green lizardLacerta viridis", "African chameleonChamaeleo chamaeleon",
"Komodo dragonKomodo lizarddragon lizardgiant lizardVaranus komodoensis",
"African crocodileNile crocodileCrocodylus niloticus", "American alligatorAlligator mississipiensis",
"triceratops", "thunder snakeworm snakeCarphophis amoenus", "ringneck snakering-necked snakering snake",
"hognose snakepuff addersand viper", "green snakegrass snake", "king snakekingsnake",
"garter snakegrass snake", "water snake", "vine snake", "night snakeHypsiglena torquata",
"boa constrictorConstrictor constrictor", "rock pythonrock snakePython sebae",
"Indian cobraNaja naja", "green mamba", "sea snake",
"horned vipercerastessand viperhorned aspCerastes cornutus",
"diamondbackdiamondback rattlesnakeCrotalus adamanteus",
"sidewinderhorned rattlesnakeCrotalus cerastes", "trilobite",
"harvestmandaddy longlegsPhalangium opilio", "scorpion",
"black and gold garden spiderArgiope aurantia", "barn spiderAraneus cavaticus",
"garden spiderAranea diademata", "black widowLatrodectus mactans", "tarantula",
"wolf spiderhunting spider", "tick", "centipede", "black grouse", "ptarmigan",
"ruffed grousepartridgeBonasa umbellus", "prairie chickenprairie grouseprairie fowl",
"peacock", "quail", "partridge", "African greyAfrican grayPsittacus erithacus",
"macaw", "sulphur-crested cockatooKakatoe galeritaCacatua galerita", "lorikeet",
"coucal", "bee eater", "hornbill", "hummingbird", "jacamar", "toucan", "drake",
"red-breasted merganserMergus serrator", "goose", "black swanCygnus atratus",
"tusker", "echidnaspiny anteateranteater",
"platypusduckbillduckbilled platypusduck-billed platypusOrnithorhynchus anatinus",
"wallabybrush kangaroo", "koalakoala bearkangaroo bearnative bearPhascolarctos cinereus",
"wombat", "jellyfish", "sea anemoneanemone", "brain coral", "flatwormplatyhelminth",
"nematodenematode wormroundworm", "conch", "snail", "slug", "sea slugnudibranch",
"chitoncoat-of-mail shellsea cradlepolyplacophore", "chambered nautiluspearly nautilusnautilus",
"Dungeness crabCancer magister", "rock crabCancer irroratus",
"fiddler crab", "king crabAlaska crabAlaskan king crabAlaska king crabParalithodes camtschatica",
"American lobsterNorthern lobsterMaine lobsterHomarus americanus",
"spiny lobsterlangousterock lobstercrawfishcrayfishsea crawfish",
"crayfishcrawfishcrawdadcrawdaddy", "hermit crab", "isopod",
"white storkCiconia ciconia", "black storkCiconia nigra",
"spoonbill", "flamingo", "little blue heronEgretta caerulea",
"American egretgreat white heronEgretta albus", "bittern", "crane",
"limpkinAramus pictus", "European gallinulePorphyrio porphyrio",
"American cootmarsh henmud henwater henFulica americana", "bustard",
"ruddy turnstoneArenaria interpres", "red-backed sandpiperdunlinErolia alpina",
"redshankTringa totanus", "dowitcher", "oystercatcheroyster catcher", "pelican",
"king penguinAptenodytes patagonica", "albatrossmollymawk",
"grey whalegray whaledevilfishEschrichtius gibbosusEschrichtius robustus",
"killer whalekillerorcagrampussea wolfOrcinus orca", "dugongDugong dugon",
"sea lion", "Chihuahua", "Japanese spaniel", "Maltese dogMaltese terrierMaltese",
"PekinesePekingesePeke", "Shih-Tzu", "Blenheim spaniel", "papillon", "toy terrier",
"Rhodesian ridgeback", "Afghan houndAfghan", "bassetbasset hound", "beagle",
"bloodhound sleuthhound", "bluetick", "black-and-tan coonhound", "Walker houndWalker foxhound",
"English foxhound", "redbone", "borzoiRussian wolfhound", "Irish wolfhound", "Italian greyhound",
"whippet", "Ibizan houndIbizan Podenco", "Norwegian elkhoundelkhound", "otterhoundotter hound",
"Salukigazelle hound", "Scottish deerhounddeerhound", "Weimaraner",
"Staffordshire bullterrierStaffordshire bull terrier",
"American Staffordshire terrierStaffordshire terrierAmerican pit bull terrierpit bull terrier",
"Bedlington terrier", "Border terrier", "Kerry blue terrier", "Irish terrier",
"Norfolk terrier", "Norwich terrier", "Yorkshire terrier", "wire-haired fox terrier",
"Lakeland terrier", "Sealyham terrierSealyham", "AiredaleAiredale terrier",
"cairncairn terrier", "Australian terrier", "Dandie DinmontDandie Dinmont terrier",
"Boston bullBoston terrier", "miniature schnauzer", "giant schnauzer",
"standard schnauzer", "Scotch terrierScottish terrierScottie", "Tibetan terrierchrysanthemum dog",
"silky terrierSydney silky", "soft-coated wheaten terrier", "West Highland white terrier",
"LhasaLhasa apso", "flat-coated retriever", "curly-coated retriever", "golden retriever",
"Labrador retriever", "Chesapeake Bay retriever", "German short-haired pointer",
"vizslaHungarian pointer", "English setter", "Irish setterred setter", "Gordon setter",
"Brittany spaniel", "clumberclumber spaniel", "English springerEnglish springer spaniel",
"Welsh springer spaniel", "cocker spanielEnglish cocker spanielcocker", "Sussex spaniel",
"Irish water spaniel", "kuvasz", "schipperke", "groenendael", "malinois", "briard", "kelpie",
"komondor", "Old English sheepdogbobtail", "Shetland sheepdogShetland sheep dogShetland",
"collie", "Border collie", "Bouvier des FlandresBouviers des Flandres", "Rottweiler",
"German shepherdGerman shepherd dogGerman police dogalsatian", "DobermanDoberman pinscher",
"miniature pinscher", "Greater Swiss Mountain dog", "Bernese mountain dog", "Appenzeller",
"EntleBucher", "boxer", "bull mastiff", "Tibetan mastiff", "French bulldog", "Great Dane",
"Saint BernardSt Bernard", "Eskimo doghusky", "malamutemalemuteAlaskan malamute", "Siberian husky",
"dalmatiancoach dogcarriage dog", "affenpinschermonkey pinschermonkey dog", "basenji", "pugpug-dog",
"Leonberg", "NewfoundlandNewfoundland dog", "Great Pyrenees", "SamoyedSamoyede", "Pomeranian",
"chowchow chow", "keeshond", "Brabancon griffon", "PembrokePembroke Welsh corgi",
"CardiganCardigan Welsh corgi", "toy poodle", "miniature poodle", "standard poodle",
"Mexican hairless", "timber wolfgrey wolfgray wolfCanis lupus",
"white wolfArctic wolfCanis lupus tundrarum",
"red wolfmaned wolfCanis rufusCanis niger", "coyoteprairie wolfbrush wolfCanis latrans",
"dingowarrigalwarragalCanis dingo", "dholeCuon alpinus",
"African hunting doghyena dogCape hunting dogLycaon pictus", "hyenahyaena", "red foxVulpes vulpes",
"kit foxVulpes macrotis", "Arctic foxwhite foxAlopex lagopus", "grey foxgray foxUrocyon cinereoargenteus",
"tabbytabby cat", "tiger cat", "Persian cat", "Siamese catSiamese", "Egyptian cat",
"cougarpumacatamountmountain lionpainterpantherFelis concolor", "lynxcatamount", "leopardPanthera pardus",
"snow leopardouncePanthera uncia", "jaguarpantherPanthera oncaFelis onca", "lionking of beastsPanthera leo",
"tigerPanthera tigris", "cheetahchetahAcinonyx jubatus", "brown bearbruinUrsus arctos",
"American black bearblack bearUrsus americanusEuarctos americanus",
"ice bearpolar bearUrsus MaritimusThalarctos maritimus", "sloth bearMelursus ursinusUrsus ursinus",
"mongoose", "meerkatmierkat", "tiger beetle", "ladybugladybeetlelady beetleladybirdladybird beetle",
"ground beetlecarabid beetle", "long-horned beetlelongicornlongicorn beetle", "leaf beetlechrysomelid",
"dung beetle", "rhinoceros beetle", "weevil", "fly", "bee", "antemmetpismire", "grasshopperhopper",
"cricket", "walking stickwalkingstickstick insect", "cockroachroach", "mantismantid", "cicadacicala",
"leafhopper", "lacewinglacewing fly",
"dragonflydarning needledevil's darning needlesewing needlesnake feedersnake doctormosquito hawkskeeter hawk",
"damselfly", "admiral", "ringletringlet butterfly", "monarchmonarch butterflymilkweed butterflyDanaus plexippus",
"cabbage butterfly", "sulphur butterflysulfur butterfly", "lycaenidlycaenid butterfly", "starfishsea star",
"sea urchin", "sea cucumberholothurian", "wood rabbitcottontailcottontail rabbit", "hare", "AngoraAngora rabbit",
"hamster", "porcupinehedgehog", "fox squirreleastern fox squirrelSciurus niger", "marmot", "beaver",
"guinea pigCavia cobaya", "sorrel", "zebra", "hogpiggruntersquealerSus scrofa", "wild boarboarSus scrofa",
"warthog", "hippopotamushipporiver horseHippopotamus amphibius", "ox",
"water buffalowater oxAsiatic buffaloBubalus bubalis", "bison", "ramtup",
"bighornbighorn sheepcimarronRocky Mountain bighornRocky Mountain sheepOvis canadensis", "ibexCapra ibex",
"hartebeest", "impalaAepyceros melampus", "gazelle", "Arabian cameldromedaryCamelus dromedarius", "llama",
"weasel", "mink", "polecatfitchfoulmartfoumartMustela putorius", "black-footed ferretferretMustela nigripes",
"otter", "skunkpolecatwood pussy", "badger", "armadillo", "three-toed slothaiBradypus tridactylus",
"orangutanorangorangutangPongo pygmaeus", "gorillaGorilla gorilla", "chimpanzeechimpPan troglodytes",
"gibbonHylobates lar", "siamangHylobates syndactylusSymphalangus syndactylus", "guenonguenon monkey",
"patashussar monkeyErythrocebus patas", "baboon", "macaque", "langur", "colobuscolobus monkey",
"proboscis monkeyNasalis larvatus", "marmoset", "capuchinringtailCebus capucinus", "howler monkeyhowler",
"titititi monkey", "spider monkeyAteles geoffroyi", "squirrel monkeySaimiri sciureus",
"Madagascar catring-tailed lemurLemur catta", "indriindrisIndri indriIndri brevicaudatus",
"Indian elephantElephas maximus", "African elephantLoxodonta africana",
"lesser pandared pandapandabear catcat bearAilurus fulgens",
"giant pandapandapanda bearcoon bearAiluropoda melanoleuca",
"barracoutasnoek", "eel", "cohocohoecoho salmonblue jacksilver salmonOncorhynchus kisutch",
"rock beautyHolocanthus tricolor", "anemone fish", "sturgeon", "gargarfishgarpikebillfishLepisosteus osseus",
"lionfish", "pufferpufferfishblowfishglobefish", "abacus", "abaya", "academic gownacademic robejudge's robe",
"accordionpiano accordionsqueeze box", "acoustic guitar", "aircraft carriercarrierflattopattack aircraft carrier",
"airliner", "airshipdirigible", "altar", "ambulance", "amphibianamphibious vehicle", "analog clock",
"apiarybee house", "apron", "ashcantrash cangarbage canwastebinash binash-binashbindustbintrash barreltrash bin",
"assault rifleassault gun", "backpackback packknapsackpacksackrucksackhaversack", "bakerybakeshopbakehouse",
"balance beambeam", "balloon", "ballpointballpoint penballpenBiro", "Band Aid", "banjo",
"bannisterbanisterbalustradebalustershandrail", "barbell", "barber chair", "barbershop",
"barn", "barometer", "barrelcask", "barrowgarden cartlawn cartwheelbarrow", "baseball", "basketball",
"bassinet", "bassoon", "bathing capswimming cap", "bath towel", "bathtubbathing tubbathtub",
"beach wagonstation wagonwagonestate carbeach waggonstation waggonwaggon", "beaconlighthousebeacon lightpharos",
"beaker", "bearskinbusbyshako", "beer bottle", "beer glass", "bell cotebell cot", "bib",
"bicycle-built-for-twotandem bicycletandem", "bikinitwo-piece", "binderring-binder",
"binocularsfield glassesopera glasses", "birdhouse", "boathouse", "bobsledbobsleighbob",
"bolo tiebolobola tiebola", "bonnetpoke bonnet", "bookcase", "bookshopbookstorebookstall",
"bottlecap", "bow", "bow tiebow-tiebowtie", "brassmemorial tabletplaque", "brassierebrabandeau",
"breakwatergroingroynemolebulwarkseawalljetty", "breastplateaegisegis", "broom", "bucketpail", "buckle",
"bulletproof vest", "bullet trainbullet", "butcher shopmeat market", "cabhacktaxitaxicab", "caldroncauldron",
"candletaperwax light", "cannon", "canoe", "can openertin opener", "cardigan", "car mirror",
"carouselcarrouselmerry-go-roundroundaboutwhirligig", "carpenter's kittool kit", "carton", "car wheel",
"cash machinecash dispenserautomated teller machineautomatic teller machineautomated tellerautomatic tellerATM",
"cassette", "cassette player", "castle", "catamaran", "CD player", "cellovioloncello",
"cellular telephonecellular phonecellphonecellmobile phone", "chain", "chainlink fence",
"chain mailring mailmailchain armorchain armourring armorring armour", "chain sawchainsaw", "chest",
"chiffoniercommode", "chimebellgong", "china cabinetchina closet", "Christmas stocking", "churchchurch building",
"cinemamovie theatermovie theatremovie housepicture palace", "cleavermeat cleaverchopper", "cliff dwelling",
"cloak", "cloggetapattensabot", "cocktail shaker", "coffee mug", "coffeepot", "coilspiralvolutewhorlhelix",
"combination lock", "computer keyboardkeypad", "confectioneryconfectionarycandy store",
"container shipcontainershipcontainer vessel", "convertible", "corkscrewbottle screw", "cornethorntrumpettrump",
"cowboy boot", "cowboy hatten-gallon hat", "cradle", "crane", "crash helmet", "crate", "cribcot", "Crock Pot",
"croquet ball", "crutch", "cuirass", "damdikedyke", "desk", "desktop computer", "dial telephonedial phone",
"diapernappynapkin", "digital clock", "digital watch", "dining tableboard", "dishragdishcloth",
"dishwasherdish washerdishwashing machine", "disk brakedisc brake", "dockdockagedocking facility",
"dogsleddog sleddog sleigh", "dome", "doormatwelcome mat", "drilling platformoffshore rig",
"drummembranophonetympan", "drumstick", "dumbbell", "Dutch oven", "electric fanblower", "electric guitar",
"electric locomotive", "entertainment center", "envelope", "espresso maker", "face powder", "feather boaboa",
"filefile cabinetfiling cabinet", "fireboat", "fire enginefire truck", "fire screenfireguard", "flagpoleflagstaff",
"flutetransverse flute", "folding chair", "football helmet", "forklift", "fountain", "fountain pen", "four-poster",
"freight car", "French hornhorn", "frying panfrypanskillet", "fur coat", "garbage truckdustcart",
"gasmaskrespiratorgas helmet", "gas pumpgasoline pumppetrol pumpisland dispenser", "goblet", "go-kart", "golf ball",
"golfcartgolf cart", "gondola", "gongtam-tam", "gown", "grand pianogrand", "greenhousenurseryglasshouse",
"grilleradiator grille", "grocery storegroceryfood marketmarket", "guillotine", "hair slide", "hair spray",
"half track", "hammer", "hamper", "hand blowerblow dryerblow drierhair dryerhair drier",
"hand-held computerhand-held microcomputer", "handkerchiefhankiehankyhankey", "hard dischard diskfixed disk",
"harmonicamouth organharpmouth harp", "harp", "harvesterreaper", "hatchet", "holster", "home theaterhome theatre",
"honeycomb", "hookclaw", "hoopskirtcrinoline", "horizontal barhigh bar", "horse carthorse-cart", "hourglass",
"iPod", "ironsmoothing iron", "jack-o'-lantern", "jeanblue jeandenim", "jeeplandrover", "jerseyT-shirttee shirt",
"jigsaw puzzle", "jinrikisharicksharickshaw", "joystick", "kimono", "knee pad", "knot", "lab coatlaboratory coat",
"ladle", "lampshadelamp shade", "laptoplaptop computer", "lawn mowermower", "lens caplens cover",
"letter openerpaper knifepaperknife", "library", "lifeboat", "lighterlightigniterignitor", "limousinelimo",
"linerocean liner", "lipsticklip rouge", "Loafer", "lotion",
"loudspeakerspeakerspeaker unitloudspeaker systemspeaker system",
"loupejeweler's loupe", "lumbermillsawmill", "magnetic compass", "mailbagpostbag",
"mailboxletter box", "maillot", "maillottank suit", "manhole cover", "maraca",
"marimbaxylophone", "mask", "matchstick", "maypole", "mazelabyrinth", "measuring cup",
"medicine chestmedicine cabinet", "megalithmegalithic structure", "microphonemike",
"microwavemicrowave oven", "military uniform", "milk can", "minibus", "miniskirtmini", "minivan", "missile",
"mitten", "mixing bowl", "mobile homemanufactured home", "Model T", "modem", "monastery", "monitor", "moped",
"mortar", "mortarboard", "mosque", "mosquito net", "motor scooterscooter", "mountain bikeall-terrain bikeoff-roader",
"mountain tent", "mousecomputer mouse", "mousetrap", "moving van", "muzzle", "nail", "neck brace", "necklace",
"nipple", "notebooknotebook computer", "obelisk", "oboehautboyhautbois", "ocarinasweet potato",
"odometerhodometermileometermilometer", "oil filter", "organpipe organ",
"oscilloscopescopecathode-ray oscilloscopeCRO", "overskirt", "oxcart", "oxygen mask", "packet",
"paddleboat paddle", "paddlewheelpaddle wheel", "padlock", "paintbrush", "pajamapyjamapj'sjammies",
"palace", "panpipepandean pipesyrinx", "paper towel", "parachutechute", "parallel barsbars",
"park bench", "parking meter", "passenger carcoachcarriage", "patioterrace", "pay-phonepay-station",
"pedestalplinthfootstall", "pencil boxpencil case", "pencil sharpener", "perfumeessence", "Petri dish",
"photocopier", "pickplectrumplectron", "pickelhaube", "picket fencepaling", "pickuppickup truck", "pier",
"piggy bankpenny bank", "pill bottle", "pillow", "ping-pong ball", "pinwheel", "piratepirate ship",
"pitcherewer", "planecarpenter's planewoodworking plane", "planetarium", "plastic bag", "plate rack", "plowplough",
"plungerplumber's helper", "Polaroid cameraPolaroid Land camera", "pole",
"police vanpolice wagonpaddy wagonpatrol wagonwagonblack Maria", "poncho", "pool tablebilliard tablesnooker table",
"pop bottlesoda bottle", "potflowerpot", "potter's wheel", "power drill", "prayer rugprayer mat", "printer",
"prisonprison house", "projectilemissile", "projector", "puckhockey puck",
"punching bagpunch bagpunching ballpunchball", "purse", "quillquill pen", "quiltcomfortercomfortpuff",
"racerrace carracing car", "racketracquet", "radiator", "radiowireless", "radio telescoperadio reflector",
"rain barrel", "recreational vehicleRVR.V.", "reel", "reflex camera", "refrigeratoricebox", "remote controlremote",
"restauranteating houseeating placeeatery", "revolversix-gunsix-shooter", "rifle", "rocking chairrocker",
"rotisserie", "rubber eraserrubberpencil eraser", "rugby ball", "ruleruler", "running shoe", "safe", "safety pin",
"saltshakersalt shaker", "sandal", "sarong", "saxsaxophone", "scabbard", "scaleweighing machine", "school bus",
"schooner", "scoreboard", "screenCRT screen", "screw", "screwdriver", "seat beltseatbelt", "sewing machine",
"shieldbuckler", "shoe shopshoe-shopshoe store", "shoji", "shopping basket", "shopping cart", "shovel",
"shower cap", "shower curtain", "ski", "ski mask", "sleeping bag", "slide ruleslipstick", "sliding door",
"slotone-armed bandit", "snorkel", "snowmobile", "snowplowsnowplough", "soap dispenser", "soccer ball",
"sock", "solar dishsolar collectorsolar furnace", "sombrero", "soup bowl", "space bar", "space heater",
"space shuttle", "spatula", "speedboat", "spider webspider's web", "spindle", "sports carsport car",
"spotlightspot", "stage", "steam locomotive", "steel arch bridge", "steel drum", "stethoscope", "stole",
"stone wall", "stopwatchstop watch", "stove", "strainer", "streetcartramtramcartrolleytrolley car", "stretcher",
"studio couchday bed", "stupatope", "submarinepigboatsubU-boat", "suitsuit of clothes", "sundial", "sunglass",
"sunglassesdark glassesshades", "sunscreensunblocksun blocker", "suspension bridge", "swabswobmop", "sweatshirt",
"swimming trunksbathing trunks", "swing", "switchelectric switchelectrical switch", "syringe", "table lamp",
"tankarmy tankarmored combat vehiclearmoured combat vehicle", "tape player", "teapot", "teddyteddy bear",
"televisiontelevision system", "tennis ball", "thatchthatched roof", "theater curtaintheatre curtain",
"thimble", "thresherthrasherthreshing machine", "throne", "tile roof", "toaster",
"tobacco shoptobacconist shoptobacconist", "toilet seat", "torch", "totem pole", "tow trucktow carwrecker",
"toyshop", "tractor", "trailer trucktractor trailertrucking rigrigarticulated lorrysemi", "tray", "trench coat",
"tricycletrikevelocipede", "trimaran", "tripod", "triumphal arch", "trolleybustrolley coachtrackless trolley",
"trombone", "tubvat", "turnstile", "typewriter keyboard", "umbrella", "unicyclemonocycle", "uprightupright piano",
"vacuumvacuum cleaner", "vase", "vault", "velvet", "vending machine", "vestment", "viaduct", "violinfiddle",
"volleyball", "waffle iron", "wall clock", "walletbillfoldnotecasepocketbook", "wardrobeclosetpress",
"warplanemilitary plane", "washbasinhandbasinwashbowllavabowash-hand basin", "washerautomatic washerwashing machine",
"water bottle", "water jug", "water tower", "whiskey jug", "whistle", "wig", "window screen", "window shade",
"Windsor tie", "wine bottle", "wing", "wok", "wooden spoon", "woolwoolenwoollen",
"worm fencesnake fencesnake-rail fenceVirginia fence", "wreck", "yawl", "yurt", "web sitewebsiteinternet sitesite",
"comic book", "crossword puzzlecrossword", "street sign", "traffic lighttraffic signalstoplight",
"book jacketdust coverdust jacketdust wrapper", "menu", "plate", "guacamole", "consomme", "hot pothotpot",
"trifle", "ice creamicecream", "ice lollylollylollipoppopsicle", "French loaf", "bagelbeigel", "pretzel",
"cheeseburger", "hotdoghot dogred hot", "mashed potato", "head cabbage", "broccoli", "cauliflower",
"zucchinicourgette", "spaghetti squash", "acorn squash", "butternut squash", "cucumbercuke",
"artichokeglobe artichoke", "bell pepper", "cardoon", "mushroom", "Granny Smith", "strawberry",
"orange", "lemon", "fig", "pineappleananas", "banana", "jackfruitjakjack", "custard apple",
"pomegranate", "hay", "carbonara", "chocolate saucechocolate syrup", "dough", "meat loafmeatloaf",
"pizzapizza pie", "potpie", "burrito", "red wine", "espresso", "cup", "eggnog", "alp", "bubble",
"cliffdropdrop-off", "coral reef", "geyser", "lakesidelakeshore", "promontoryheadlandheadforeland",
"sandbarsand bar", "seashorecoastseacoastsea-coast", "valleyvale", "volcano", "ballplayerbaseball player",
"groombridegroom", "scuba diver", "rapeseed", "daisy",
"yellow lady's slipperyellow lady-slipperCypripedium calceolusCypripedium parviflorum", "corn", "acorn",
"hiprose hiprosehip", "buckeyehorse chestnutconker", "coral fungus", "agaric", "gyromitra",
"stinkhorncarrion fungus", "earthstar", "hen-of-the-woodshen of the woodsPolyporus frondosusGrifola frondosa",
"bolete", "earspikecapitulum", "toilet tissuetoilet paperbathroom tissue"};
#endif // modelInference_label_H
